create table PMS_I_PAGE_IQUIRY_MATEXIST_AMT（
  id           NUMBER(19) not null, 
  ENTITY_CREATE_DATE Date, 
  ENTITY_UPDATE_DATE Date, 
  INVENTORY_ORG_CODE VARCHAR2(50),
  INVENTORY_ORG_NAME VARCHAR2(100),
  SUBINVENTORY VARCHAR2(100),
  ORG_ID NUMBER,
  ORG_NAME VARCHAR2(100),
  LOCATION_NAME VARCHAR2(100),
  INVEST_SUBJECT VARCHAR2(20),
  PROJECT_CODE VARCHAR2(50),
  PROJECT_NAME VARCHAR2(100),
  MATERIAL_CODE VARCHAR2(50),
  MATERIAL_NAME VARCHAR2(100),
  UNIT VARCHAR2(20),
  EXIST_AMOUNT NUMBER,
  AVAILABLE_AMOUNT NUMBER,
  BATCH_NUM VARCHAR2(50),
  INBOUND_TIME DATE,
  OUTPUT_EXT VARCHAR2(2000)
);
comment on table PMS_I_PAGE_IQUIRY_MATEXIST_AMT
  is '查询SCM库存现有量信息路由服务';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.ENTITY_CREATE_DATE
  is '数据更新时间';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.ENTITY_UPDATE_DATE
  is '数据创建时间';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.INVENTORY_ORG_CODE
  is '库存组织编码';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.INVENTORY_ORG_NAME
  is '库存组织名称';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.SUBINVENTORY
  is '子库存';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.ORG_ID
  is 'OU组织ID';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.ORG_NAME
  is 'OU组织名称';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.LOCATION_NAME
  is '货位名称';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.INVEST_SUBJECT
  is '投资主体';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.PROJECT_CODE
  is '项目编码';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.PROJECT_NAME
  is '项目名称';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.MATERIAL_CODE
  is '物料编码';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.MATERIAL_NAME
  is '物料名称';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.UNIT
  is '计量单位';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.EXIST_AMOUNT
  is '现有量';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.AVAILABLE_AMOUNT
  is '可用量';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.BATCH_NUM
  is '批次号';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.INBOUND_TIME
  is '入库时间';
comment on column PMS_I_PAGE_IQUIRY_MATEXIST_AMT.OUTPUT_EXT
  is '查询结果扩展';
alter table PMS_I_PAGE_IQUIRY_MATEXIST_AMT
  add constraint PRI_PAGE_IQUIRY_MATEXIST_AMT primary key (ID); 
